apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Pinca-labs
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 2
  - name: ng-2
    instanceType: t2.micro
    desiredCapacity: 2